name: canary

on:
  push:
    branches: ["canary"]

jobs:
  canary_build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - run: go version

      - name: check gh-cli user
        run: gh auth status | grep Logged
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: download Test Resources
        run: make devr
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: download Frontend
        run: make frontend
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Unit Tests
        run: |
          echo "running generate schedule test encoding individual"

          make devr
          go clean -testcache && go test -run TestEstimateResourceAvailabilityFirstSem ./GeneticAlgorithm -timeout 0

          make devr
          go clean -testcache && go test -run TestEstimateResourceAvailabilitySecondSem ./GeneticAlgorithm -timeout 0

          make devr
          go clean -testcache && go test -run TestNewPopulationFirstSem ./GeneticAlgorithm -timeout 0

          make devr
          go clean -testcache && go test -run TestNewPopulationSecondSem ./GeneticAlgorithm -timeout 0

          make devr
          go clean -testcache && go test -run TestNewPopulation1stSemWithDepartmentSelection ./GeneticAlgorithm -timeout 0

          make devr
          go clean -testcache && go test -run TestNewPopulation2ndSemWithDepartmentSelection ./GeneticAlgorithm -timeout 0

          make devr
          go clean -testcache && go test -run TestRandomMutations ./GeneticAlgorithm -timeout 0

          echo "running test resource methods"

          make devr
          go clean -testcache && go test -run Test ./Resources/Curriculum -timeout 0

          make devr
          go clean -testcache && go test -run Test ./Resources/Instructors -timeout 0

          make devr
          go clean -testcache && go test -run Test ./Resources/Rooms -timeout 0

          echo "running test schedule data structures"

          make devr
          go clean -testcache && go test -run Test ./Schedule -timeout 0

          echo "running test persistence methods"

          make devr
          go clean -testcache && go test -run Test ./StorageResources -timeout 0

          make devr
          go clean -testcache && go test -run Test ./StorageSchedule -timeout 0

          echo "running test others"

          make devr
          go clean -testcache && go test -run Test ./Tests/schedule_datastructure_basic -timeout 0

          go clean -testcache && go test -run Test ./Utils -timeout 0
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
          LOG_MODE: verbose

      - name: run Build
        run: make build

      - name: Build For Windows 64-bit Computers
        run: |
          go clean -testcache
          env GOOS=windows GOARCH=amd64 go build -tags netgo -ldflags '-s -w' -o win-64-build/scheduling-backend.exe
          cp -r dist win-64-build
          cp -r scheduling-system-temporary-data-empty win-64-build/scheduling-system-temporary-data
          zip -r win-64-build.zip win-64-build/

      - name: create github canary release
        run: gh release create canary-build-v${{ github.run_number }} dist.zip scheduling-system-temporary-data.zip win-64-build.zip --title "Canary Build" --notes "canary build version number ${{ github.run_number }}" --draft=false --prerelease=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy to canary
        if: github.ref == 'refs/heads/canary'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
